[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "arsoniztzs-pokedex"
version = "0.1.0"
description = "A basic CLI Pokédex for quick viewing of Arsoniztz's fake Pokémon."
requires-python = ">=3.9"
dependencies = [
    "click>=8.0",
    "colorama>=0.4.6",
]

[project.scripts]
a-dex = "arsoniztzs_pokedex.cli:search"

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
arsoniztzs_pokedex = ["resources/**/*"]